# Use Dockerized infrastructure
#sudo: false
os: linux

# Use node_js environnement
language: node_js
node_js:
  - stable
  - "6"

# Cache Gcloud SDK between commands
cache:
#  yarn: true
#  directories:
#  - "$HOME/google-cloud-sdk/"

env:
  global:


install:
  - npm install

script:
  - npm test

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update

  # use the decrypted service account credentials to authenticate the command line tool
  # get the encrypted variable names from travis cli: https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $encrypted_eb328a879d60_key -iv $encrypted_eb328a879d60_iv -in scenic-setup-231121-04700bd179e4.json.enc -out scenic-setup-231121-04700bd179e4.json -d
  - gcloud auth activate-service-account --key-file gcloud-service-key.json

  - gcloud config set project scenic-setup-231121

deploy:
  - provider: script
    script:
      # change PROJECT and REPO to the values from the cloud console: https://console.cloud.google.com/code/develop
      - gcloud --quiet beta functions deploy mailer --source-url https://github.com/fhafez/signin-template-node/tree/master/gcp-functions --source-path / --trigger-http
    on:
      branch: master
